/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controllers.PanelChatController;
import Controllers.PanelContactoController;
import Controllers.PanelLogginController;
import Controllers.PanelMensajesController;
import Controllers.PanelNuevoUserController;
import Controllers.PanelPrincipalController;
import Controllers.PanelUserController;
import Modelo.Usuario;

/**
 *
 * @author david_alcazar
 */
public class TelefonoView extends javax.swing.JFrame {

    /**
     * Creates new form TelefonoView
     */
    PanelLogginController logginC;
    public PanelPrincipalController pricipalC;
    PanelNuevoUserController nuevoUserC;
    PanelUserController UserC;
    PanelChatController ChatContaC;
    public PanelContactoController contactoC;
    public PanelMensajesController mensajeC;
    
    public TelefonoView() {
        initComponents();
        logginC = new PanelLogginController(this);
        pricipalC = new PanelPrincipalController(this);
        nuevoUserC = new PanelNuevoUserController(this);
        UserC = new PanelUserController(this);
        ChatContaC = new PanelChatController(this);
        contactoC = new PanelContactoController(this);
        mensajeC = new PanelMensajesController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoggin = new javax.swing.JPanel();
        jPasswordFieldLoggin = new javax.swing.JPasswordField();
        jTextFieldIngresaIP = new javax.swing.JTextField();
        jButtonIngresarLoggin = new javax.swing.JButton();
        jButtonRegistrarseLoggin = new javax.swing.JButton();
        jLabelImageLoggin = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonAgregarContacto = new javax.swing.JButton();
        jButtonBuscarContacto = new javax.swing.JButton();
        jButtonPerfil = new javax.swing.JButton();
        jButtonChats = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContac = new javax.swing.JTable();
        jTextFieldBuscarContacto = new javax.swing.JTextField();
        jLabelImagePrincipal = new javax.swing.JLabel();
        jPaneNuevoUser = new javax.swing.JPanel();
        jButtonCrearUser = new javax.swing.JButton();
        jButtonRegresarNuevoUser = new javax.swing.JButton();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldIPRegis = new javax.swing.JTextField();
        jPasswordFieldContraRegis = new javax.swing.JPasswordField();
        jLabeimagenNuevoUser = new javax.swing.JLabel();
        jPanelUser = new javax.swing.JPanel();
        jButtonUser = new javax.swing.JButton();
        jButtonChatPrincipal = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabelMageUser = new javax.swing.JLabel();
        jPanelChat = new javax.swing.JPanel();
        jButtonCerrarChats = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonNuevoContacto = new javax.swing.JButton();
        jButtonActualizarContacto = new javax.swing.JButton();
        jButtonNuevoGrupo = new javax.swing.JButton();
        jLabelImganChat = new javax.swing.JLabel();
        jPanelContacto = new javax.swing.JPanel();
        jButtonCrearContac = new javax.swing.JButton();
        jButtonRegresarContac = new javax.swing.JButton();
        jTextFieldNomContac = new javax.swing.JTextField();
        jTextFieldIPContac = new javax.swing.JTextField();
        jLabelImageContacto = new javax.swing.JLabel();
        jPanelMensajeria = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldMensaje = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jButtonRegresarMen = new javax.swing.JButton();
        jLabelNombreContac = new javax.swing.JLabel();
        jLabeImageMensajeria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLoggin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordFieldLoggin.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldLoggin.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jPasswordFieldLoggin.setForeground(new java.awt.Color(51, 102, 255));
        jPasswordFieldLoggin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldLoggin.setBorder(null);
        jPanelLoggin.add(jPasswordFieldLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 160, 30));

        jTextFieldIngresaIP.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngresaIP.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTextFieldIngresaIP.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldIngresaIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIngresaIP.setBorder(null);
        jPanelLoggin.add(jTextFieldIngresaIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 253, 160, 30));
        jPanelLoggin.add(jButtonIngresarLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 90, 30));
        jPanelLoggin.add(jButtonRegistrarseLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 120, 20));

        jLabelImageLoggin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loggin.png"))); // NOI18N
        jPanelLoggin.add(jLabelImageLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelPrincipal.add(jButtonAgregarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 50, 50));
        jPanelPrincipal.add(jButtonBuscarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 30, 30));
        jPanelPrincipal.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 70, 50));
        jPanelPrincipal.add(jButtonChats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 70, 50));

        jTableContac.setBackground(new java.awt.Color(255, 255, 255));
        jTableContac.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTableContac.setForeground(new java.awt.Color(51, 51, 255));
        jTableContac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableContac.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableContac.setAutoscrolls(false);
        jTableContac.setGridColor(new java.awt.Color(255, 255, 255));
        jTableContac.setRowHeight(65);
        jTableContac.setSelectionBackground(new java.awt.Color(51, 102, 255));
        jTableContac.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTableContac);

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, 390));

        jTextFieldBuscarContacto.setBackground(new java.awt.Color(240, 238, 238));
        jTextFieldBuscarContacto.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jTextFieldBuscarContacto.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldBuscarContacto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBuscarContacto.setBorder(null);
        jPanelPrincipal.add(jTextFieldBuscarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 180, 20));

        jLabelImagePrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal.png"))); // NOI18N
        jLabelImagePrincipal.setText("jLabel1");
        jPanelPrincipal.add(jLabelImagePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPaneNuevoUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPaneNuevoUser.add(jButtonCrearUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 90, 30));
        jPaneNuevoUser.add(jButtonRegresarNuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 60, 50));

        jTextFieldNom.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNom.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTextFieldNom.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNom.setBorder(null);
        jPaneNuevoUser.add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 160, 20));

        jTextFieldIPRegis.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIPRegis.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTextFieldIPRegis.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldIPRegis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIPRegis.setBorder(null);
        jPaneNuevoUser.add(jTextFieldIPRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 160, 30));

        jPasswordFieldContraRegis.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContraRegis.setForeground(new java.awt.Color(51, 102, 255));
        jPasswordFieldContraRegis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldContraRegis.setBorder(null);
        jPaneNuevoUser.add(jPasswordFieldContraRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 150, 20));

        jLabeimagenNuevoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevoUsuario.png"))); // NOI18N
        jLabeimagenNuevoUser.setText("jLabel1");
        jPaneNuevoUser.add(jLabeimagenNuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelUser.add(jButtonUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, 40));
        jPanelUser.add(jButtonChatPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 80, 40));
        jPanelUser.add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 110, 30));

        jLabelMageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        jPanelUser.add(jLabelMageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelChat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelChat.add(jButtonCerrarChats, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 50, 40));
        jPanelChat.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 30, 30));
        jPanelChat.add(jButtonNuevoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 203, 130, 30));
        jPanelChat.add(jButtonActualizarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 160, 20));
        jPanelChat.add(jButtonNuevoGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 110, 20));

        jLabelImganChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chat.png"))); // NOI18N
        jPanelChat.add(jLabelImganChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelContacto.add(jButtonCrearContac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 110, 30));
        jPanelContacto.add(jButtonRegresarContac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 60, 50));

        jTextFieldNomContac.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomContac.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jTextFieldNomContac.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldNomContac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNomContac.setBorder(null);
        jPanelContacto.add(jTextFieldNomContac, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 160, -1));

        jTextFieldIPContac.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIPContac.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jTextFieldIPContac.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldIPContac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIPContac.setBorder(null);
        jPanelContacto.add(jTextFieldIPContac, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 160, -1));

        jLabelImageContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contacto.jpeg"))); // NOI18N
        jPanelContacto.add(jLabelImageContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelMensajeria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(219, 219, 219));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 102, 255));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanelMensajeria.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 280, 430));

        jTextFieldMensaje.setBackground(new java.awt.Color(219, 219, 219));
        jTextFieldMensaje.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jTextFieldMensaje.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldMensaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMensaje.setBorder(null);
        jPanelMensajeria.add(jTextFieldMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 170, 20));
        jPanelMensajeria.add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 593, 30, 40));
        jPanelMensajeria.add(jButtonRegresarMen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 50));

        jLabelNombreContac.setBackground(new java.awt.Color(51, 102, 255));
        jLabelNombreContac.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabelNombreContac.setForeground(new java.awt.Color(51, 102, 255));
        jLabelNombreContac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanelMensajeria.add(jLabelNombreContac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, 20));

        jLabeImageMensajeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chat.jpeg"))); // NOI18N
        jPanelMensajeria.add(jLabeImageMensajeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoggin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPaneNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMensajeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoggin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPaneNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMensajeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelefonoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizarContacto;
    public javax.swing.JButton jButtonAgregarContacto;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonBuscarContacto;
    public javax.swing.JButton jButtonCerrarChats;
    public javax.swing.JButton jButtonCerrarSesion;
    public javax.swing.JButton jButtonChatPrincipal;
    public javax.swing.JButton jButtonChats;
    public javax.swing.JButton jButtonCrearContac;
    public javax.swing.JButton jButtonCrearUser;
    public javax.swing.JButton jButtonEnviar;
    public javax.swing.JButton jButtonIngresarLoggin;
    public javax.swing.JButton jButtonNuevoContacto;
    public javax.swing.JButton jButtonNuevoGrupo;
    public javax.swing.JButton jButtonPerfil;
    public javax.swing.JButton jButtonRegistrarseLoggin;
    public javax.swing.JButton jButtonRegresarContac;
    public javax.swing.JButton jButtonRegresarMen;
    public javax.swing.JButton jButtonRegresarNuevoUser;
    public javax.swing.JButton jButtonUser;
    private javax.swing.JLabel jLabeImageMensajeria;
    private javax.swing.JLabel jLabeimagenNuevoUser;
    private javax.swing.JLabel jLabelImageContacto;
    private javax.swing.JLabel jLabelImageLoggin;
    private javax.swing.JLabel jLabelImagePrincipal;
    private javax.swing.JLabel jLabelImganChat;
    private javax.swing.JLabel jLabelMageUser;
    public javax.swing.JLabel jLabelNombreContac;
    public javax.swing.JPanel jPaneNuevoUser;
    public javax.swing.JPanel jPanelChat;
    public javax.swing.JPanel jPanelContacto;
    public javax.swing.JPanel jPanelLoggin;
    public javax.swing.JPanel jPanelMensajeria;
    public javax.swing.JPanel jPanelPrincipal;
    public javax.swing.JPanel jPanelUser;
    public javax.swing.JPasswordField jPasswordFieldContraRegis;
    public javax.swing.JPasswordField jPasswordFieldLoggin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableContac;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextFieldBuscarContacto;
    public javax.swing.JTextField jTextFieldIPContac;
    public javax.swing.JTextField jTextFieldIPRegis;
    public javax.swing.JTextField jTextFieldIngresaIP;
    public javax.swing.JTextField jTextFieldMensaje;
    public javax.swing.JTextField jTextFieldNom;
    public javax.swing.JTextField jTextFieldNomContac;
    // End of variables declaration//GEN-END:variables
}
