/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controllers.PanelLogginController;
import Controllers.PanelPrincipalController;
import Modelo.Usuario;

/**
 *
 * @author david_alcazar
 */
public class TelefonoView extends javax.swing.JFrame {

    /**
     * Creates new form TelefonoView
     */
    PanelLogginController logginC;
    public PanelPrincipalController pricipalC;
    
    public TelefonoView() {
        initComponents();
        logginC = new PanelLogginController(this);
        pricipalC = new PanelPrincipalController(this);
        
        
//        Usuario usuario = logginC.validarInicioSesion();
//
//        if (usuario != null) {
//            
//            pricipalC.setUsuario(usuario.getIpUsuario()); 
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoggin = new javax.swing.JPanel();
        jPasswordFieldLoggin = new javax.swing.JPasswordField();
        jTextFieldIngresaIP = new javax.swing.JTextField();
        jButtonIngresarLoggin = new javax.swing.JButton();
        jButtonRegistrarseLoggin = new javax.swing.JButton();
        jLabelImageLoggin = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonAgregarContacto = new javax.swing.JButton();
        jButtonBuscarContacto = new javax.swing.JButton();
        jButtonPerfil = new javax.swing.JButton();
        jButtonChats = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContac = new javax.swing.JTable();
        jLabelImagePrincipal = new javax.swing.JLabel();
        jPaneNuevoUser = new javax.swing.JPanel();
        jLabeimagenNuevoUser = new javax.swing.JLabel();
        jPanelUser = new javax.swing.JPanel();
        jLabelMageUser = new javax.swing.JLabel();
        jPanelChat = new javax.swing.JPanel();
        jLabelImganChat = new javax.swing.JLabel();
        jPanelMensajeria = new javax.swing.JPanel();
        jLabeImageMensajeria = new javax.swing.JLabel();
        jPanelContacto = new javax.swing.JPanel();
        jLabelImageContacto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLoggin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordFieldLoggin.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldLoggin.setForeground(new java.awt.Color(51, 51, 255));
        jPasswordFieldLoggin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldLoggin.setBorder(null);
        jPanelLoggin.add(jPasswordFieldLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 160, 30));

        jTextFieldIngresaIP.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIngresaIP.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldIngresaIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIngresaIP.setBorder(null);
        jPanelLoggin.add(jTextFieldIngresaIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 253, 160, 30));
        jPanelLoggin.add(jButtonIngresarLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 90, 30));
        jPanelLoggin.add(jButtonRegistrarseLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 120, 20));

        jLabelImageLoggin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Loggin.png"))); // NOI18N
        jPanelLoggin.add(jLabelImageLoggin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelPrincipal.add(jButtonAgregarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 50, 50));
        jPanelPrincipal.add(jButtonBuscarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 30, 30));
        jPanelPrincipal.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 70, 50));
        jPanelPrincipal.add(jButtonChats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 70, 50));

        jTableContac.setBackground(new java.awt.Color(255, 255, 255));
        jTableContac.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTableContac.setForeground(new java.awt.Color(51, 51, 255));
        jTableContac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableContac.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableContac.setAutoscrolls(false);
        jTableContac.setGridColor(new java.awt.Color(255, 255, 255));
        jTableContac.setRowHeight(60);
        jTableContac.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTableContac);

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, 390));

        jLabelImagePrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal.png"))); // NOI18N
        jLabelImagePrincipal.setText("jLabel1");
        jPanelPrincipal.add(jLabelImagePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPaneNuevoUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeimagenNuevoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevoUsuario.png"))); // NOI18N
        jLabeimagenNuevoUser.setText("jLabel1");
        jPaneNuevoUser.add(jLabeimagenNuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        jPanelUser.add(jLabelMageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelChat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImganChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chat.png"))); // NOI18N
        jPanelChat.add(jLabelImganChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelMensajeria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeImageMensajeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chat.jpeg"))); // NOI18N
        jPanelMensajeria.add(jLabeImageMensajeria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        jPanelContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImageContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contacto.jpeg"))); // NOI18N
        jPanelContacto.add(jLabelImageContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoggin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPaneNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMensajeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoggin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPaneNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMensajeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelefonoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelefonoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAgregarContacto;
    public javax.swing.JButton jButtonBuscarContacto;
    public javax.swing.JButton jButtonChats;
    public javax.swing.JButton jButtonIngresarLoggin;
    public javax.swing.JButton jButtonPerfil;
    public javax.swing.JButton jButtonRegistrarseLoggin;
    private javax.swing.JLabel jLabeImageMensajeria;
    private javax.swing.JLabel jLabeimagenNuevoUser;
    private javax.swing.JLabel jLabelImageContacto;
    private javax.swing.JLabel jLabelImageLoggin;
    private javax.swing.JLabel jLabelImagePrincipal;
    private javax.swing.JLabel jLabelImganChat;
    private javax.swing.JLabel jLabelMageUser;
    public javax.swing.JPanel jPaneNuevoUser;
    public javax.swing.JPanel jPanelChat;
    public javax.swing.JPanel jPanelContacto;
    public javax.swing.JPanel jPanelLoggin;
    public javax.swing.JPanel jPanelMensajeria;
    public javax.swing.JPanel jPanelPrincipal;
    public javax.swing.JPanel jPanelUser;
    public javax.swing.JPasswordField jPasswordFieldLoggin;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableContac;
    public javax.swing.JTextField jTextFieldIngresaIP;
    // End of variables declaration//GEN-END:variables
}
